version: '3.4'

x-common:
  - &api-common
    image: ogc/routing-api:latest
    build:
      context: ./
      dockerfile: api.Dockerfile
    depends_on:
      - wps
      - mongo
  - &api-common-env
    ROUTING_ENDPOINT: http://wps:8080/rest/
    SPRING_DATA_MONGODB_HOST: mongo
    SPRING_DATA_MONGODB_PORT: 27017
    SERVER_PORT: 8000
    SERVER_USEFORWARDHEADERS: "true"

services:

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - here-api
      - ecere-api
      - skymantics-api

  here-api:
    << : *api-common
    environment:
      << : *api-common-env
      ROUTING_PROCESS: org.n52.routing.here
      SPRING_DATA_MONGODB_DATABASE: here
      SERVER_SERVLET_CONTEXTPATH: /here/

  ecere-api:
    << : *api-common
    environment:
      << : *api-common-env
      ROUTING_PROCESS: org.n52.routing.ecere
      SPRING_DATA_MONGODB_DATABASE: ecere
      SERVER_SERVLET_CONTEXTPATH: /ecere/

  skymantics-api:
    << : *api-common
    environment:
      << : *api-common-env
      ROUTING_PROCESS: org.n52.routing.skymantics
      SPRING_DATA_MONGODB_DATABASE: skymantics
      SERVER_SERVLET_CONTEXTPATH: /skymantics/

  mongo:
    image: mongo:latest

  wps:
    build:
      context: ./
      dockerfile: wps.Dockerfile
    image: ogc/routing-wps:latest
    environment:
      HERE_APP_ID: ${HERE_APP_ID}
      HERE_APP_CODE: ${HERE_APP_CODE}

