GET http://localhost:8000/
Accept: application/json
###
GET http://localhost:8000/conformance
Accept: application/json
###
GET http://localhost:8000/processes
Accept: application/json
###
GET http://localhost:8000/processes/routing
Accept: application/json
###
GET http://localhost:8080/rest/processes/org.n52.routing.here
Accept: application/json
###
GET http://localhost:8080/rest/processes/org.n52.routing.here/jobs
Accept: application/json
###
GET http://localhost:8000/processes/routing/jobs
Accept: application/json
###
POST http://localhost:8000/processes/routing/jobs
Accept: application/json
Content-Type: application/json

{
  "inputs":[
    {
      "id": "name",
      "input": { "value": "The name of the Route." }
    },
    {
      "id": "waypoints",
      "input": {
        "format": { "mimeType": "application/geo+json" },
        "value": {
          "inlineValue": {
            "type": "MultiPoint", 
            "coordinates": [
              [-77.047712, 38.892346],
              [-76.994730, 38.902629]
            ]
          }
        }
      }
    },
    {
      "id": "preference",
      "input": { 
        "value": "fastest"
      }
    }
  ],
  "outputs": [
    {
      "id": "route",
      "format": { "mimeType": "application/geo+json" },
      "transmissionMode": "value"
    }
  ]
}
###
GET http://localhost:8000/processes/routing/jobs/3002ffee-5b54-4772-8589-31ab8e18895c
Accept: application/json
###
GET http://localhost:8000/processes/routing/jobs/3002ffee-5b54-4772-8589-31ab8e18895c/result
Accept: application/json
###
GET http://localhost:8000/routes
Accept: application/json
###
POST http://localhost:8000/routes?mode=async
Content-Type: application/json

{
  "name": "The name of the Route.",
  "preference": "fastest",
  "waypoints": {
    "type": "MultiPoint",
    "coordinates": [
      [-77.047712,38.892346],
      [-76.99473,38.902629]
    ]
  }
}
###
POST http://localhost:8000/routes?mode=sync
Content-Type: application/json

{
  "name": "The name of the Route.",
  "preference": "fastest",
  "waypoints": {
    "type": "MultiPoint",
    "coordinates": [
      [-77.047712,38.892346],
      [-76.99473,38.902629]
    ]
  }
}
###
GET http://localhost:8000/routes/5d3597e24cedfd0001f0f92a
Accept: application/json
###
GET http://localhost:8000/routes/5d3597e24cedfd0001f0f92a/definition
Accept: application/json